;;; Exercise 1.9
;;; Illustrate the process generated by each procedure in evaluating (+ 4 5)

#lang scheme

(define (inc a)
  (+ a 1))

(define (dec a)
  (- a 1))

;Procedure 1
(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

;Procedure 2
(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

;Procedure 1 evaluation - linear recursive process
; (+ 4 5)
; (inc (+ 3 5))
; (inc (inc (+ 2 5))
; (inc (inc (inc(+ 1 5)))
; (inc (inc (inc (inc (+ 0 5))))
; (inc (inc (inc (inc 5))))
; (inc (inc (inc 6)))
; . . .
; 9

;Procedure 2 evaluation - linear iterative process
; (+ 4 5)
; (+ 3 6)
; (+ 2 7)
; (+ 1 8)
; (+ 0 9)
; 9


